Converting Python3 bytes_string to regular string
Making sure json.loads() get feed regular strings by adding
decode("utf-8") at a few places where it was missing.
If not doing this I encountered errors like:
TypeError: the JSON object must be str, not 'bytes'

Change-Id: I5960c8301781194cdbd23d54c00c0712fa3afa1d