Fixing some undefined functions and cold/hot/warm copy/paste errors
Fixing some errors like:
NameError: name 'BinaryToWIF' is not defined

I guess the problems occured due to incomplete refactoring.

Change-Id: I3dbe84938085a8839ff665b6d2e757246b438318